<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-181TTAT" failures="4" tests="36" name="Test_All_Modules_edge" time="257.511" errors="0" timestamp="2025-08-17T00:09:25 GMT-04:00">
  <testcase classname="testCases.Stack" name="open_stac_page" time="0.714"/>
  <testcase classname="testCases.Queue" name="open_queue_page" time="0.878"/>
  <testcase classname="testCases.Stack" name="stackOperations" time="1.163"/>
  <testcase classname="testCases.Queue" name="queueImplementation" time="1.149"/>
  <testcase classname="testCases.Stack" name="stackoperationsCodeEditor" time="1.737"/>
  <testcase classname="testCases.Queue" name="queueImplementationCodeEditor" time="2.093"/>
  <testcase classname="testCases.Stack" name="StackTryingEmptyEditor" time="2.414">
    <skipped/>
  </testcase> <!-- StackTryingEmptyEditor -->
  <testcase classname="testCases.Stack" name="StackTryingEmptyEditor" time="1.986">
    <skipped/>
  </testcase> <!-- StackTryingEmptyEditor -->
  <testcase classname="testCases.Stack" name="StackTryingEmptyEditor" time="1.955">
    <skipped/>
  </testcase> <!-- StackTryingEmptyEditor -->
  <testcase classname="testCases.Stack" name="StackTryingEmptyEditor" time="2.297">
    <failure type="java.lang.AssertionError" message="Failing this test case to show the bug which is, no alert message comes up when clicking on run button without entering anhy code in it">
      <![CDATA[java.lang.AssertionError: Failing this test case to show the bug which is, no alert message comes up when clicking on run button without entering anhy code in it
at testCases.Stack.StackTryingEmptyEditor(Stack.java:78)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- StackTryingEmptyEditor -->
  <testcase classname="testCases.Queue" name="queueTryingEmptyEditor" time="2.718">
    <skipped/>
  </testcase> <!-- queueTryingEmptyEditor -->
  <testcase classname="testCases.Queue" name="queueTryingEmptyEditor" time="1.881">
    <skipped/>
  </testcase> <!-- queueTryingEmptyEditor -->
  <testcase classname="testCases.Queue" name="queueTryingEmptyEditor" time="2.147">
    <skipped/>
  </testcase> <!-- queueTryingEmptyEditor -->
  <testcase classname="testCases.Queue" name="queueTryingEmptyEditor" time="2.095">
    <failure type="java.lang.AssertionError" message="Failing this test case to show the bug which is, no alert message comes up when clicking on run button without entering anhy code in it">
      <![CDATA[java.lang.AssertionError: Failing this test case to show the bug which is, no alert message comes up when clicking on run button without entering anhy code in it
at testCases.Queue.queueTryingEmptyEditor(Queue.java:80)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- queueTryingEmptyEditor -->
  <testcase classname="testCases.Stack" name="StackTryingValidAndInvalidCode" time="2.299"/>
  <testcase classname="testCases.Stack" name="StackTryingValidAndInvalidCode" time="1.937"/>
  <testcase classname="testCases.Queue" name="queueTryingValidAndInvalidCode" time="2.645"/>
  <testcase classname="testCases.Queue" name="queueTryingValidAndInvalidCode" time="2.026"/>
  <testcase classname="testCases.Stack" name="stackimplementation" time="1.115"/>
  <testcase classname="testCases.Queue" name="queueImplementationUsingCollection" time="0.997"/>
  <testcase classname="testCases.Stack" name="stackimplementationCodeEditor" time="1.644"/>
  <testcase classname="testCases.Queue" name="queueImplementationUsingCollectionCodeEditor" time="1.581"/>
  <testcase classname="testCases.Stack" name="stackapplication" time="1.173"/>
  <testcase classname="testCases.Queue" name="queueImplementationUsingArray" time="0.873"/>
  <testcase classname="testCases.Stack" name="stackapplicationCodeEditor" time="1.737"/>
  <testcase classname="testCases.Queue" name="queueImplementationUsingArrayCodeEditor" time="1.663"/>
  <testcase classname="testCases.Stack" name="StackopenPracticeQuestions" time="1.311">
    <skipped/>
  </testcase> <!-- StackopenPracticeQuestions -->
  <testcase classname="testCases.Stack" name="StackopenPracticeQuestions" time="2.129">
    <skipped/>
  </testcase> <!-- StackopenPracticeQuestions -->
  <testcase classname="testCases.Stack" name="StackopenPracticeQuestions" time="1.462">
    <skipped/>
  </testcase> <!-- StackopenPracticeQuestions -->
  <testcase classname="testCases.Stack" name="StackopenPracticeQuestions" time="2.087">
    <failure type="java.lang.AssertionError" message="Failing this test case to show the bug which is,there are no practice questions available for stack module">
      <![CDATA[java.lang.AssertionError: Failing this test case to show the bug which is,there are no practice questions available for stack module
at testCases.Stack.StackopenPracticeQuestions(Stack.java:160)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- StackopenPracticeQuestions -->
  <testcase classname="testCases.Queue" name="queueOperations" time="0.912"/>
  <testcase classname="testCases.Queue" name="queueOperationsCodeEditor" time="1.903"/>
  <testcase classname="testCases.Queue" name="queueOpenPracticeQuestions" time="1.787">
    <skipped/>
  </testcase> <!-- queueOpenPracticeQuestions -->
  <testcase classname="testCases.Queue" name="queueOpenPracticeQuestions" time="1.896">
    <skipped/>
  </testcase> <!-- queueOpenPracticeQuestions -->
  <testcase classname="testCases.Queue" name="queueOpenPracticeQuestions" time="2.284">
    <skipped/>
  </testcase> <!-- queueOpenPracticeQuestions -->
  <testcase classname="testCases.Queue" name="queueOpenPracticeQuestions" time="1.869">
    <failure type="java.lang.AssertionError" message="Failing this test case to show the bug which is,there are no practice questions available for queue module">
      <![CDATA[java.lang.AssertionError: Failing this test case to show the bug which is,there are no practice questions available for queue module
at testCases.Queue.queueOpenPracticeQuestions(Queue.java:181)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- queueOpenPracticeQuestions -->
</testsuite> <!-- Test_All_Modules_edge -->
