<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-181TTAT" failures="6" tests="57" name="testCases.Queue" time="467.710" errors="0" timestamp="2025-08-17T00:11:45 GMT-04:00" skipped="18">
  <testcase classname="testCases.Queue" name="open_queue_page" time="5.511"/>
  <system-out/>
  <testcase classname="testCases.Queue" name="open_queue_page" time="7.091"/>
  <system-out/>
  <testcase classname="testCases.Queue" name="open_queue_page" time="11.781"/>
  <system-out/>
  <testcase classname="testCases.Queue" name="queueImplementation" time="5.935"/>
  <system-out/>
  <testcase classname="testCases.Queue" name="queueImplementation" time="5.509"/>
  <system-out/>
  <testcase classname="testCases.Queue" name="queueImplementation" time="11.536"/>
  <system-out/>
  <testcase classname="testCases.Queue" name="queueImplementationCodeEditor" time="5.757"/>
  <system-out/>
  <testcase classname="testCases.Queue" name="queueImplementationCodeEditor" time="6.853"/>
  <system-out/>
  <testcase classname="testCases.Queue" name="queueImplementationCodeEditor" time="16.193"/>
  <system-out/>
  <testcase classname="testCases.Queue" name="queueTryingEmptyEditor" time="8.013">
    <skipped/>
  </testcase> <!-- queueTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.Queue" name="queueTryingEmptyEditor" time="10.461">
    <failure message="Failing this test case to show the bug which is, no alert message comes up when clicking on run button without entering anhy code in it" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Failing this test case to show the bug which is, no alert message comes up when clicking on run button without entering anhy code in it
at org.testng.Assert.fail(Assert.java:110)
at testCases.Queue.queueTryingEmptyEditor(Queue.java:80)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- queueTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.Queue" name="queueTryingEmptyEditor" time="6.580">
    <failure message="Failing this test case to show the bug which is, no alert message comes up when clicking on run button without entering anhy code in it" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Failing this test case to show the bug which is, no alert message comes up when clicking on run button without entering anhy code in it
at org.testng.Assert.fail(Assert.java:110)
at testCases.Queue.queueTryingEmptyEditor(Queue.java:80)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- queueTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.Queue" name="queueTryingEmptyEditor" time="9.273">
    <skipped/>
  </testcase> <!-- queueTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.Queue" name="queueTryingEmptyEditor" time="14.140">
    <skipped/>
  </testcase> <!-- queueTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.Queue" name="queueTryingEmptyEditor" time="6.708">
    <skipped/>
  </testcase> <!-- queueTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.Queue" name="queueTryingEmptyEditor" time="6.636">
    <failure message="Failing this test case to show the bug which is, no alert message comes up when clicking on run button without entering anhy code in it" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Failing this test case to show the bug which is, no alert message comes up when clicking on run button without entering anhy code in it
at org.testng.Assert.fail(Assert.java:110)
at testCases.Queue.queueTryingEmptyEditor(Queue.java:80)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- queueTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.Queue" name="queueTryingEmptyEditor" time="13.696">
    <skipped/>
  </testcase> <!-- queueTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.Queue" name="queueTryingEmptyEditor" time="6.627">
    <skipped/>
  </testcase> <!-- queueTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.Queue" name="queueTryingEmptyEditor" time="7.487">
    <skipped/>
  </testcase> <!-- queueTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.Queue" name="queueTryingEmptyEditor" time="7.440">
    <skipped/>
  </testcase> <!-- queueTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.Queue" name="queueTryingEmptyEditor" time="7.890">
    <skipped/>
  </testcase> <!-- queueTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.Queue" name="queueTryingValidAndInvalidCode" time="11.867"/>
  <system-out/>
  <testcase classname="testCases.Queue" name="queueTryingValidAndInvalidCode" time="7.778"/>
  <system-out/>
  <testcase classname="testCases.Queue" name="queueTryingValidAndInvalidCode" time="6.382"/>
  <system-out/>
  <testcase classname="testCases.Queue" name="queueTryingValidAndInvalidCode" time="8.146"/>
  <system-out/>
  <testcase classname="testCases.Queue" name="queueTryingValidAndInvalidCode" time="8.223"/>
  <system-out/>
  <testcase classname="testCases.Queue" name="queueTryingValidAndInvalidCode" time="9.154"/>
  <system-out/>
  <testcase classname="testCases.Queue" name="queueImplementationUsingCollection" time="7.541"/>
  <system-out/>
  <testcase classname="testCases.Queue" name="queueImplementationUsingCollection" time="6.601"/>
  <system-out/>
  <testcase classname="testCases.Queue" name="queueImplementationUsingCollection" time="11.278"/>
  <system-out/>
  <testcase classname="testCases.Queue" name="queueImplementationUsingCollectionCodeEditor" time="8.328"/>
  <system-out/>
  <testcase classname="testCases.Queue" name="queueImplementationUsingCollectionCodeEditor" time="7.963"/>
  <system-out/>
  <testcase classname="testCases.Queue" name="queueImplementationUsingCollectionCodeEditor" time="6.384"/>
  <system-out/>
  <testcase classname="testCases.Queue" name="queueImplementationUsingArray" time="6.097"/>
  <system-out/>
  <testcase classname="testCases.Queue" name="queueImplementationUsingArray" time="5.941"/>
  <system-out/>
  <testcase classname="testCases.Queue" name="queueImplementationUsingArray" time="11.733"/>
  <system-out/>
  <testcase classname="testCases.Queue" name="queueImplementationUsingArrayCodeEditor" time="6.906"/>
  <system-out/>
  <testcase classname="testCases.Queue" name="queueImplementationUsingArrayCodeEditor" time="7.360"/>
  <system-out/>
  <testcase classname="testCases.Queue" name="queueImplementationUsingArrayCodeEditor" time="13.475"/>
  <system-out/>
  <testcase classname="testCases.Queue" name="queueOperations" time="7.630"/>
  <system-out/>
  <testcase classname="testCases.Queue" name="queueOperations" time="6.131"/>
  <system-out/>
  <testcase classname="testCases.Queue" name="queueOperations" time="7.302"/>
  <system-out/>
  <testcase classname="testCases.Queue" name="queueOperationsCodeEditor" time="6.865"/>
  <system-out/>
  <testcase classname="testCases.Queue" name="queueOperationsCodeEditor" time="7.943"/>
  <system-out/>
  <testcase classname="testCases.Queue" name="queueOperationsCodeEditor" time="8.377"/>
  <system-out/>
  <testcase classname="testCases.Queue" name="queueOpenPracticeQuestions" time="7.815">
    <failure message="Failing this test case to show the bug which is,there are no practice questions available for queue module" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Failing this test case to show the bug which is,there are no practice questions available for queue module
at org.testng.Assert.fail(Assert.java:110)
at testCases.Queue.queueOpenPracticeQuestions(Queue.java:181)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- queueOpenPracticeQuestions -->
  <system-out/>
  <testcase classname="testCases.Queue" name="queueOpenPracticeQuestions" time="5.732">
    <skipped/>
  </testcase> <!-- queueOpenPracticeQuestions -->
  <system-out/>
  <testcase classname="testCases.Queue" name="queueOpenPracticeQuestions" time="6.712">
    <skipped/>
  </testcase> <!-- queueOpenPracticeQuestions -->
  <system-out/>
  <testcase classname="testCases.Queue" name="queueOpenPracticeQuestions" time="7.231">
    <failure message="Failing this test case to show the bug which is,there are no practice questions available for queue module" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Failing this test case to show the bug which is,there are no practice questions available for queue module
at org.testng.Assert.fail(Assert.java:110)
at testCases.Queue.queueOpenPracticeQuestions(Queue.java:181)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- queueOpenPracticeQuestions -->
  <system-out/>
  <testcase classname="testCases.Queue" name="queueOpenPracticeQuestions" time="5.673">
    <skipped/>
  </testcase> <!-- queueOpenPracticeQuestions -->
  <system-out/>
  <testcase classname="testCases.Queue" name="queueOpenPracticeQuestions" time="7.505">
    <skipped/>
  </testcase> <!-- queueOpenPracticeQuestions -->
  <system-out/>
  <testcase classname="testCases.Queue" name="queueOpenPracticeQuestions" time="6.638">
    <skipped/>
  </testcase> <!-- queueOpenPracticeQuestions -->
  <system-out/>
  <testcase classname="testCases.Queue" name="queueOpenPracticeQuestions" time="7.061">
    <skipped/>
  </testcase> <!-- queueOpenPracticeQuestions -->
  <system-out/>
  <testcase classname="testCases.Queue" name="queueOpenPracticeQuestions" time="9.365">
    <skipped/>
  </testcase> <!-- queueOpenPracticeQuestions -->
  <system-out/>
  <testcase classname="testCases.Queue" name="queueOpenPracticeQuestions" time="6.727">
    <skipped/>
  </testcase> <!-- queueOpenPracticeQuestions -->
  <system-out/>
  <testcase classname="testCases.Queue" name="queueOpenPracticeQuestions" time="12.472">
    <skipped/>
  </testcase> <!-- queueOpenPracticeQuestions -->
  <system-out/>
  <testcase classname="testCases.Queue" name="queueOpenPracticeQuestions" time="8.257">
    <failure message="Failing this test case to show the bug which is,there are no practice questions available for queue module" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Failing this test case to show the bug which is,there are no practice questions available for queue module
at org.testng.Assert.fail(Assert.java:110)
at testCases.Queue.queueOpenPracticeQuestions(Queue.java:181)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- queueOpenPracticeQuestions -->
  <system-out/>
</testsuite> <!-- testCases.Queue -->
