<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-181TTAT" failures="2" tests="19" name="testCases.QueueTest" time="108.207" errors="0" timestamp="2025-08-24T13:59:14 GMT-04:00" skipped="6">
  <testcase classname="testCases.QueueTest" name="open_queue_page" time="4.297"/>
  <system-out/>
  <testcase classname="testCases.QueueTest" name="queueImplementation" time="4.435"/>
  <system-out/>
  <testcase classname="testCases.QueueTest" name="queueImplementationCodeEditor" time="12.415"/>
  <system-out/>
  <testcase classname="testCases.QueueTest" name="queueTryingEmptyEditor" time="7.609">
    <skipped/>
  </testcase> <!-- queueTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.QueueTest" name="queueTryingEmptyEditor" time="6.474">
    <failure message="Failing this test case to show the bug which is, no alert message comes up when clicking on run button without entering any code in it" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Failing this test case to show the bug which is, no alert message comes up when clicking on run button without entering any code in it
at org.testng.Assert.fail(Assert.java:110)
at testCases.QueueTest.queueTryingEmptyEditor(QueueTest.java:75)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- queueTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.QueueTest" name="queueTryingEmptyEditor" time="8.082">
    <skipped/>
  </testcase> <!-- queueTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.QueueTest" name="queueTryingEmptyEditor" time="6.150">
    <skipped/>
  </testcase> <!-- queueTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.QueueTest" name="queueTryingValidAndInvalidCode" time="5.626"/>
  <system-out/>
  <testcase classname="testCases.QueueTest" name="queueTryingValidAndInvalidCode" time="5.205"/>
  <system-out/>
  <testcase classname="testCases.QueueTest" name="queueImplementationUsingCollection" time="4.095"/>
  <system-out/>
  <testcase classname="testCases.QueueTest" name="queueImplementationUsingCollectionCodeEditor" time="6.357"/>
  <system-out/>
  <testcase classname="testCases.QueueTest" name="queueImplementationUsingArray" time="4.850"/>
  <system-out/>
  <testcase classname="testCases.QueueTest" name="queueImplementationUsingArrayCodeEditor" time="4.854"/>
  <system-out/>
  <testcase classname="testCases.QueueTest" name="queueOperations" time="4.811"/>
  <system-out/>
  <testcase classname="testCases.QueueTest" name="queueOperationsCodeEditor" time="4.751"/>
  <system-out/>
  <testcase classname="testCases.QueueTest" name="queueOpenPracticeQuestions" time="5.006">
    <skipped/>
  </testcase> <!-- queueOpenPracticeQuestions -->
  <system-out/>
  <testcase classname="testCases.QueueTest" name="queueOpenPracticeQuestions" time="4.443">
    <failure message="Failing this test case to show the bug which is,there are no practice questions available for queue module" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Failing this test case to show the bug which is,there are no practice questions available for queue module
at org.testng.Assert.fail(Assert.java:110)
at testCases.QueueTest.queueOpenPracticeQuestions(QueueTest.java:161)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- queueOpenPracticeQuestions -->
  <system-out/>
  <testcase classname="testCases.QueueTest" name="queueOpenPracticeQuestions" time="4.224">
    <skipped/>
  </testcase> <!-- queueOpenPracticeQuestions -->
  <system-out/>
  <testcase classname="testCases.QueueTest" name="queueOpenPracticeQuestions" time="4.523">
    <skipped/>
  </testcase> <!-- queueOpenPracticeQuestions -->
  <system-out/>
</testsuite> <!-- testCases.QueueTest -->
