<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-181TTAT" failures="6" tests="57" name="testCases.Queue" time="438.424" errors="0" timestamp="2025-08-15T10:14:31 GMT-04:00" skipped="18">
  <testcase classname="testCases.Queue" name="open_queue_page" time="6.696"/>
  <system-out/>
  <testcase classname="testCases.Queue" name="open_queue_page" time="6.046"/>
  <system-out/>
  <testcase classname="testCases.Queue" name="open_queue_page" time="7.371"/>
  <system-out/>
  <testcase classname="testCases.Queue" name="queueImplementation" time="3.903"/>
  <system-out/>
  <testcase classname="testCases.Queue" name="queueImplementation" time="6.042"/>
  <system-out/>
  <testcase classname="testCases.Queue" name="queueImplementation" time="15.233"/>
  <system-out/>
  <testcase classname="testCases.Queue" name="queueImplementationCodeEditor" time="9.547"/>
  <system-out/>
  <testcase classname="testCases.Queue" name="queueImplementationCodeEditor" time="5.871"/>
  <system-out/>
  <testcase classname="testCases.Queue" name="queueImplementationCodeEditor" time="7.545"/>
  <system-out/>
  <testcase classname="testCases.Queue" name="queueTryingEmptyEditor" time="7.375">
    <skipped/>
  </testcase> <!-- queueTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.Queue" name="queueTryingEmptyEditor" time="7.688">
    <skipped/>
  </testcase> <!-- queueTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.Queue" name="queueTryingEmptyEditor" time="16.637">
    <skipped/>
  </testcase> <!-- queueTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.Queue" name="queueTryingEmptyEditor" time="17.378">
    <skipped/>
  </testcase> <!-- queueTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.Queue" name="queueTryingEmptyEditor" time="6.242">
    <failure message="Failing this test case to show the bug which is, no alert message comes up when clicking on run button without entering anhy code in it" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Failing this test case to show the bug which is, no alert message comes up when clicking on run button without entering anhy code in it
at org.testng.Assert.fail(Assert.java:110)
at testCases.Queue.queueTryingEmptyEditor(Queue.java:71)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- queueTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.Queue" name="queueTryingEmptyEditor" time="8.191">
    <skipped/>
  </testcase> <!-- queueTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.Queue" name="queueTryingEmptyEditor" time="7.635">
    <failure message="Failing this test case to show the bug which is, no alert message comes up when clicking on run button without entering anhy code in it" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Failing this test case to show the bug which is, no alert message comes up when clicking on run button without entering anhy code in it
at org.testng.Assert.fail(Assert.java:110)
at testCases.Queue.queueTryingEmptyEditor(Queue.java:71)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- queueTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.Queue" name="queueTryingEmptyEditor" time="7.156">
    <skipped/>
  </testcase> <!-- queueTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.Queue" name="queueTryingEmptyEditor" time="8.384">
    <failure message="Failing this test case to show the bug which is, no alert message comes up when clicking on run button without entering anhy code in it" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Failing this test case to show the bug which is, no alert message comes up when clicking on run button without entering anhy code in it
at org.testng.Assert.fail(Assert.java:110)
at testCases.Queue.queueTryingEmptyEditor(Queue.java:71)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- queueTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.Queue" name="queueTryingEmptyEditor" time="7.867">
    <skipped/>
  </testcase> <!-- queueTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.Queue" name="queueTryingEmptyEditor" time="9.245">
    <skipped/>
  </testcase> <!-- queueTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.Queue" name="queueTryingEmptyEditor" time="7.785">
    <skipped/>
  </testcase> <!-- queueTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.Queue" name="queueTryingValidAndInvalidCode" time="18.167"/>
  <system-out/>
  <testcase classname="testCases.Queue" name="queueTryingValidAndInvalidCode" time="5.112"/>
  <system-out/>
  <testcase classname="testCases.Queue" name="queueTryingValidAndInvalidCode" time="5.128"/>
  <system-out/>
  <testcase classname="testCases.Queue" name="queueTryingValidAndInvalidCode" time="9.058"/>
  <system-out/>
  <testcase classname="testCases.Queue" name="queueTryingValidAndInvalidCode" time="7.107"/>
  <system-out/>
  <testcase classname="testCases.Queue" name="queueTryingValidAndInvalidCode" time="7.449"/>
  <system-out/>
  <testcase classname="testCases.Queue" name="queueImplementationUsingCollection" time="4.429"/>
  <system-out/>
  <testcase classname="testCases.Queue" name="queueImplementationUsingCollection" time="5.759"/>
  <system-out/>
  <testcase classname="testCases.Queue" name="queueImplementationUsingCollection" time="6.504"/>
  <system-out/>
  <testcase classname="testCases.Queue" name="queueImplementationUsingCollectionCodeEditor" time="7.197"/>
  <system-out/>
  <testcase classname="testCases.Queue" name="queueImplementationUsingCollectionCodeEditor" time="11.128"/>
  <system-out/>
  <testcase classname="testCases.Queue" name="queueImplementationUsingCollectionCodeEditor" time="9.236"/>
  <system-out/>
  <testcase classname="testCases.Queue" name="queueImplementationUsingArray" time="7.373"/>
  <system-out/>
  <testcase classname="testCases.Queue" name="queueImplementationUsingArray" time="7.240"/>
  <system-out/>
  <testcase classname="testCases.Queue" name="queueImplementationUsingArray" time="4.606"/>
  <system-out/>
  <testcase classname="testCases.Queue" name="queueImplementationUsingArrayCodeEditor" time="4.816"/>
  <system-out/>
  <testcase classname="testCases.Queue" name="queueImplementationUsingArrayCodeEditor" time="6.089"/>
  <system-out/>
  <testcase classname="testCases.Queue" name="queueImplementationUsingArrayCodeEditor" time="7.695"/>
  <system-out/>
  <testcase classname="testCases.Queue" name="queueOperations" time="6.444"/>
  <system-out/>
  <testcase classname="testCases.Queue" name="queueOperations" time="5.105"/>
  <system-out/>
  <testcase classname="testCases.Queue" name="queueOperations" time="13.000"/>
  <system-out/>
  <testcase classname="testCases.Queue" name="queueOperationsCodeEditor" time="8.213"/>
  <system-out/>
  <testcase classname="testCases.Queue" name="queueOperationsCodeEditor" time="4.889"/>
  <system-out/>
  <testcase classname="testCases.Queue" name="queueOperationsCodeEditor" time="8.685"/>
  <system-out/>
  <testcase classname="testCases.Queue" name="queueOpenPracticeQuestions" time="4.700">
    <skipped/>
  </testcase> <!-- queueOpenPracticeQuestions -->
  <system-out/>
  <testcase classname="testCases.Queue" name="queueOpenPracticeQuestions" time="3.349">
    <skipped/>
  </testcase> <!-- queueOpenPracticeQuestions -->
  <system-out/>
  <testcase classname="testCases.Queue" name="queueOpenPracticeQuestions" time="4.854">
    <skipped/>
  </testcase> <!-- queueOpenPracticeQuestions -->
  <system-out/>
  <testcase classname="testCases.Queue" name="queueOpenPracticeQuestions" time="4.595">
    <failure message="Failing this test case to show the bug which is,there are no practice questions available for queue module" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Failing this test case to show the bug which is,there are no practice questions available for queue module
at org.testng.Assert.fail(Assert.java:110)
at testCases.Queue.queueOpenPracticeQuestions(Queue.java:170)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- queueOpenPracticeQuestions -->
  <system-out/>
  <testcase classname="testCases.Queue" name="queueOpenPracticeQuestions" time="6.450">
    <skipped/>
  </testcase> <!-- queueOpenPracticeQuestions -->
  <system-out/>
  <testcase classname="testCases.Queue" name="queueOpenPracticeQuestions" time="6.140">
    <skipped/>
  </testcase> <!-- queueOpenPracticeQuestions -->
  <system-out/>
  <testcase classname="testCases.Queue" name="queueOpenPracticeQuestions" time="6.403">
    <skipped/>
  </testcase> <!-- queueOpenPracticeQuestions -->
  <system-out/>
  <testcase classname="testCases.Queue" name="queueOpenPracticeQuestions" time="7.758">
    <failure message="Failing this test case to show the bug which is,there are no practice questions available for queue module" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Failing this test case to show the bug which is,there are no practice questions available for queue module
at org.testng.Assert.fail(Assert.java:110)
at testCases.Queue.queueOpenPracticeQuestions(Queue.java:170)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- queueOpenPracticeQuestions -->
  <system-out/>
  <testcase classname="testCases.Queue" name="queueOpenPracticeQuestions" time="4.179">
    <skipped/>
  </testcase> <!-- queueOpenPracticeQuestions -->
  <system-out/>
  <testcase classname="testCases.Queue" name="queueOpenPracticeQuestions" time="7.872">
    <skipped/>
  </testcase> <!-- queueOpenPracticeQuestions -->
  <system-out/>
  <testcase classname="testCases.Queue" name="queueOpenPracticeQuestions" time="15.578">
    <failure message="Failing this test case to show the bug which is,there are no practice questions available for queue module" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Failing this test case to show the bug which is,there are no practice questions available for queue module
at org.testng.Assert.fail(Assert.java:110)
at testCases.Queue.queueOpenPracticeQuestions(Queue.java:170)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- queueOpenPracticeQuestions -->
  <system-out/>
  <testcase classname="testCases.Queue" name="queueOpenPracticeQuestions" time="6.280">
    <skipped/>
  </testcase> <!-- queueOpenPracticeQuestions -->
  <system-out/>
</testsuite> <!-- testCases.Queue -->
