<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-181TTAT" failures="3" tests="42" name="testCases.Stack" time="282.055" errors="0" timestamp="2025-08-14T17:31:39 GMT-04:00" skipped="9">
  <testcase classname="testCases.Stack" name="open_stac_page" time="4.736"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="open_stac_page" time="10.882"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="open_stac_page" time="5.680"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="stackOperations" time="4.681"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="stackOperations" time="6.250"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="stackOperations" time="4.382"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="stackoperationsCodeEditor" time="8.486"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="stackoperationsCodeEditor" time="5.752"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="stackoperationsCodeEditor" time="5.830"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="StackTryingEmptyEditor" time="5.790">
    <skipped/>
  </testcase> <!-- StackTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.Stack" name="StackTryingEmptyEditor" time="5.701">
    <failure message="Failing this test case to show the bug which is, no alert message comes up when clicking on run button without entering anhy code in it" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Failing this test case to show the bug which is, no alert message comes up when clicking on run button without entering anhy code in it
at org.testng.Assert.fail(Assert.java:110)
at testCases.Stack.StackTryingEmptyEditor(Stack.java:72)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- StackTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.Stack" name="StackTryingEmptyEditor" time="6.104">
    <skipped/>
  </testcase> <!-- StackTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.Stack" name="StackTryingEmptyEditor" time="5.325">
    <skipped/>
  </testcase> <!-- StackTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.Stack" name="StackTryingEmptyEditor" time="11.993">
    <skipped/>
  </testcase> <!-- StackTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.Stack" name="StackTryingEmptyEditor" time="5.456">
    <skipped/>
  </testcase> <!-- StackTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.Stack" name="StackTryingEmptyEditor" time="6.398">
    <skipped/>
  </testcase> <!-- StackTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.Stack" name="StackTryingEmptyEditor" time="7.210">
    <skipped/>
  </testcase> <!-- StackTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.Stack" name="StackTryingEmptyEditor" time="5.820">
    <skipped/>
  </testcase> <!-- StackTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.Stack" name="StackTryingEmptyEditor" time="8.534">
    <failure message="Failing this test case to show the bug which is, no alert message comes up when clicking on run button without entering anhy code in it" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Failing this test case to show the bug which is, no alert message comes up when clicking on run button without entering anhy code in it
at org.testng.Assert.fail(Assert.java:110)
at testCases.Stack.StackTryingEmptyEditor(Stack.java:72)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- StackTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.Stack" name="StackTryingEmptyEditor" time="6.146">
    <failure message="Failing this test case to show the bug which is, no alert message comes up when clicking on run button without entering anhy code in it" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Failing this test case to show the bug which is, no alert message comes up when clicking on run button without entering anhy code in it
at org.testng.Assert.fail(Assert.java:110)
at testCases.Stack.StackTryingEmptyEditor(Stack.java:72)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- StackTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.Stack" name="StackTryingEmptyEditor" time="12.804">
    <skipped/>
  </testcase> <!-- StackTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.Stack" name="StackTryingValidAndInvalidCode" time="6.410"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="StackTryingValidAndInvalidCode" time="5.870"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="StackTryingValidAndInvalidCode" time="6.577"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="StackTryingValidAndInvalidCode" time="6.623"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="StackTryingValidAndInvalidCode" time="10.335"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="StackTryingValidAndInvalidCode" time="6.145"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="stackimplementation" time="5.701"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="stackimplementation" time="5.335"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="stackimplementation" time="12.538"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="stackimplementationCodeEditor" time="10.487"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="stackimplementationCodeEditor" time="5.472"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="stackimplementationCodeEditor" time="5.166"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="stackapplication" time="5.061"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="stackapplication" time="5.785"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="stackapplication" time="3.988"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="stackapplicationCodeEditor" time="5.494"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="stackapplicationCodeEditor" time="5.242"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="stackapplicationCodeEditor" time="9.348"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="StackopenPracticeQuestions" time="5.651"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="StackopenPracticeQuestions" time="6.043"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="StackopenPracticeQuestions" time="4.824"/>
  <system-out/>
</testsuite> <!-- testCases.Stack -->
