<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-181TTAT" failures="6" tests="57" name="testCases.QueueTest" time="394.268" errors="0" timestamp="2025-08-17T00:39:27 GMT-04:00" skipped="18">
  <testcase classname="testCases.QueueTest" name="open_queue_page" time="4.622"/>
  <system-out/>
  <testcase classname="testCases.QueueTest" name="open_queue_page" time="3.914"/>
  <system-out/>
  <testcase classname="testCases.QueueTest" name="open_queue_page" time="11.235"/>
  <system-out/>
  <testcase classname="testCases.QueueTest" name="queueImplementation" time="5.867"/>
  <system-out/>
  <testcase classname="testCases.QueueTest" name="queueImplementation" time="7.364"/>
  <system-out/>
  <testcase classname="testCases.QueueTest" name="queueImplementation" time="4.660"/>
  <system-out/>
  <testcase classname="testCases.QueueTest" name="queueImplementationCodeEditor" time="8.403"/>
  <system-out/>
  <testcase classname="testCases.QueueTest" name="queueImplementationCodeEditor" time="5.690"/>
  <system-out/>
  <testcase classname="testCases.QueueTest" name="queueImplementationCodeEditor" time="5.288"/>
  <system-out/>
  <testcase classname="testCases.QueueTest" name="queueTryingEmptyEditor" time="6.134">
    <skipped/>
  </testcase> <!-- queueTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.QueueTest" name="queueTryingEmptyEditor" time="9.149">
    <skipped/>
  </testcase> <!-- queueTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.QueueTest" name="queueTryingEmptyEditor" time="10.299">
    <skipped/>
  </testcase> <!-- queueTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.QueueTest" name="queueTryingEmptyEditor" time="7.463">
    <skipped/>
  </testcase> <!-- queueTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.QueueTest" name="queueTryingEmptyEditor" time="6.589">
    <failure message="Failing this test case to show the bug which is, no alert message comes up when clicking on run button without entering anhy code in it" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Failing this test case to show the bug which is, no alert message comes up when clicking on run button without entering anhy code in it
at org.testng.Assert.fail(Assert.java:110)
at testCases.QueueTest.queueTryingEmptyEditor(QueueTest.java:80)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- queueTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.QueueTest" name="queueTryingEmptyEditor" time="5.630">
    <skipped/>
  </testcase> <!-- queueTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.QueueTest" name="queueTryingEmptyEditor" time="6.487">
    <skipped/>
  </testcase> <!-- queueTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.QueueTest" name="queueTryingEmptyEditor" time="8.426">
    <failure message="Failing this test case to show the bug which is, no alert message comes up when clicking on run button without entering anhy code in it" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Failing this test case to show the bug which is, no alert message comes up when clicking on run button without entering anhy code in it
at org.testng.Assert.fail(Assert.java:110)
at testCases.QueueTest.queueTryingEmptyEditor(QueueTest.java:80)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- queueTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.QueueTest" name="queueTryingEmptyEditor" time="6.274">
    <skipped/>
  </testcase> <!-- queueTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.QueueTest" name="queueTryingEmptyEditor" time="5.989">
    <skipped/>
  </testcase> <!-- queueTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.QueueTest" name="queueTryingEmptyEditor" time="12.483">
    <skipped/>
  </testcase> <!-- queueTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.QueueTest" name="queueTryingEmptyEditor" time="7.393">
    <failure message="Failing this test case to show the bug which is, no alert message comes up when clicking on run button without entering anhy code in it" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Failing this test case to show the bug which is, no alert message comes up when clicking on run button without entering anhy code in it
at org.testng.Assert.fail(Assert.java:110)
at testCases.QueueTest.queueTryingEmptyEditor(QueueTest.java:80)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- queueTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.QueueTest" name="queueTryingValidAndInvalidCode" time="7.103"/>
  <system-out/>
  <testcase classname="testCases.QueueTest" name="queueTryingValidAndInvalidCode" time="6.396"/>
  <system-out/>
  <testcase classname="testCases.QueueTest" name="queueTryingValidAndInvalidCode" time="5.644"/>
  <system-out/>
  <testcase classname="testCases.QueueTest" name="queueTryingValidAndInvalidCode" time="10.600"/>
  <system-out/>
  <testcase classname="testCases.QueueTest" name="queueTryingValidAndInvalidCode" time="10.495"/>
  <system-out/>
  <testcase classname="testCases.QueueTest" name="queueTryingValidAndInvalidCode" time="7.845"/>
  <system-out/>
  <testcase classname="testCases.QueueTest" name="queueImplementationUsingCollection" time="4.681"/>
  <system-out/>
  <testcase classname="testCases.QueueTest" name="queueImplementationUsingCollection" time="6.411"/>
  <system-out/>
  <testcase classname="testCases.QueueTest" name="queueImplementationUsingCollection" time="4.814"/>
  <system-out/>
  <testcase classname="testCases.QueueTest" name="queueImplementationUsingCollectionCodeEditor" time="5.830"/>
  <system-out/>
  <testcase classname="testCases.QueueTest" name="queueImplementationUsingCollectionCodeEditor" time="6.707"/>
  <system-out/>
  <testcase classname="testCases.QueueTest" name="queueImplementationUsingCollectionCodeEditor" time="5.620"/>
  <system-out/>
  <testcase classname="testCases.QueueTest" name="queueImplementationUsingArray" time="6.138"/>
  <system-out/>
  <testcase classname="testCases.QueueTest" name="queueImplementationUsingArray" time="7.967"/>
  <system-out/>
  <testcase classname="testCases.QueueTest" name="queueImplementationUsingArray" time="5.207"/>
  <system-out/>
  <testcase classname="testCases.QueueTest" name="queueImplementationUsingArrayCodeEditor" time="7.050"/>
  <system-out/>
  <testcase classname="testCases.QueueTest" name="queueImplementationUsingArrayCodeEditor" time="6.275"/>
  <system-out/>
  <testcase classname="testCases.QueueTest" name="queueImplementationUsingArrayCodeEditor" time="11.229"/>
  <system-out/>
  <testcase classname="testCases.QueueTest" name="queueOperations" time="6.795"/>
  <system-out/>
  <testcase classname="testCases.QueueTest" name="queueOperations" time="5.665"/>
  <system-out/>
  <testcase classname="testCases.QueueTest" name="queueOperations" time="5.940"/>
  <system-out/>
  <testcase classname="testCases.QueueTest" name="queueOperationsCodeEditor" time="5.581"/>
  <system-out/>
  <testcase classname="testCases.QueueTest" name="queueOperationsCodeEditor" time="6.282"/>
  <system-out/>
  <testcase classname="testCases.QueueTest" name="queueOperationsCodeEditor" time="8.694"/>
  <system-out/>
  <testcase classname="testCases.QueueTest" name="queueOpenPracticeQuestions" time="6.273">
    <skipped/>
  </testcase> <!-- queueOpenPracticeQuestions -->
  <system-out/>
  <testcase classname="testCases.QueueTest" name="queueOpenPracticeQuestions" time="8.000">
    <skipped/>
  </testcase> <!-- queueOpenPracticeQuestions -->
  <system-out/>
  <testcase classname="testCases.QueueTest" name="queueOpenPracticeQuestions" time="4.668">
    <failure message="Failing this test case to show the bug which is,there are no practice questions available for queue module" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Failing this test case to show the bug which is,there are no practice questions available for queue module
at org.testng.Assert.fail(Assert.java:110)
at testCases.QueueTest.queueOpenPracticeQuestions(QueueTest.java:181)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- queueOpenPracticeQuestions -->
  <system-out/>
  <testcase classname="testCases.QueueTest" name="queueOpenPracticeQuestions" time="5.577">
    <skipped/>
  </testcase> <!-- queueOpenPracticeQuestions -->
  <system-out/>
  <testcase classname="testCases.QueueTest" name="queueOpenPracticeQuestions" time="5.931">
    <skipped/>
  </testcase> <!-- queueOpenPracticeQuestions -->
  <system-out/>
  <testcase classname="testCases.QueueTest" name="queueOpenPracticeQuestions" time="5.727">
    <skipped/>
  </testcase> <!-- queueOpenPracticeQuestions -->
  <system-out/>
  <testcase classname="testCases.QueueTest" name="queueOpenPracticeQuestions" time="9.306">
    <failure message="Failing this test case to show the bug which is,there are no practice questions available for queue module" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Failing this test case to show the bug which is,there are no practice questions available for queue module
at org.testng.Assert.fail(Assert.java:110)
at testCases.QueueTest.queueOpenPracticeQuestions(QueueTest.java:181)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- queueOpenPracticeQuestions -->
  <system-out/>
  <testcase classname="testCases.QueueTest" name="queueOpenPracticeQuestions" time="6.033">
    <failure message="Failing this test case to show the bug which is,there are no practice questions available for queue module" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Failing this test case to show the bug which is,there are no practice questions available for queue module
at org.testng.Assert.fail(Assert.java:110)
at testCases.QueueTest.queueOpenPracticeQuestions(QueueTest.java:181)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- queueOpenPracticeQuestions -->
  <system-out/>
  <testcase classname="testCases.QueueTest" name="queueOpenPracticeQuestions" time="7.877">
    <skipped/>
  </testcase> <!-- queueOpenPracticeQuestions -->
  <system-out/>
  <testcase classname="testCases.QueueTest" name="queueOpenPracticeQuestions" time="8.047">
    <skipped/>
  </testcase> <!-- queueOpenPracticeQuestions -->
  <system-out/>
  <testcase classname="testCases.QueueTest" name="queueOpenPracticeQuestions" time="6.402">
    <skipped/>
  </testcase> <!-- queueOpenPracticeQuestions -->
  <system-out/>
  <testcase classname="testCases.QueueTest" name="queueOpenPracticeQuestions" time="6.099">
    <skipped/>
  </testcase> <!-- queueOpenPracticeQuestions -->
  <system-out/>
</testsuite> <!-- testCases.QueueTest -->
