<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-181TTAT" failures="3" tests="24" name="testCases.Stack" time="161.910" errors="0" timestamp="2025-08-12T08:32:29 GMT-04:00" skipped="9">
  <testcase classname="testCases.Stack" name="open_stac_page" time="9.863"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="open_stac_page" time="5.128"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="open_stac_page" time="4.820"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="stackOperations" time="5.890"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="stackOperations" time="5.212"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="stackOperations" time="5.823"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="StackoperationsTryingEmptyEditor" time="5.986">
    <skipped/>
  </testcase> <!-- StackoperationsTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.Stack" name="StackoperationsTryingEmptyEditor" time="6.280">
    <skipped/>
  </testcase> <!-- StackoperationsTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.Stack" name="StackoperationsTryingEmptyEditor" time="6.652">
    <skipped/>
  </testcase> <!-- StackoperationsTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.Stack" name="StackoperationsTryingEmptyEditor" time="5.406">
    <skipped/>
  </testcase> <!-- StackoperationsTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.Stack" name="StackoperationsTryingEmptyEditor" time="10.679">
    <skipped/>
  </testcase> <!-- StackoperationsTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.Stack" name="StackoperationsTryingEmptyEditor" time="6.122">
    <failure message="Failing this test case to show the bug which is, no alert message comes up when clicking on run button without entering anhy code in it" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Failing this test case to show the bug which is, no alert message comes up when clicking on run button without entering anhy code in it
at org.testng.Assert.fail(Assert.java:110)
at testCases.Stack.StackoperationsTryingEmptyEditor(Stack.java:70)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- StackoperationsTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.Stack" name="StackoperationsTryingEmptyEditor" time="6.405">
    <failure message="Failing this test case to show the bug which is, no alert message comes up when clicking on run button without entering anhy code in it" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Failing this test case to show the bug which is, no alert message comes up when clicking on run button without entering anhy code in it
at org.testng.Assert.fail(Assert.java:110)
at testCases.Stack.StackoperationsTryingEmptyEditor(Stack.java:70)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- StackoperationsTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.Stack" name="StackoperationsTryingEmptyEditor" time="11.473">
    <failure message="Failing this test case to show the bug which is, no alert message comes up when clicking on run button without entering anhy code in it" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Failing this test case to show the bug which is, no alert message comes up when clicking on run button without entering anhy code in it
at org.testng.Assert.fail(Assert.java:110)
at testCases.Stack.StackoperationsTryingEmptyEditor(Stack.java:70)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- StackoperationsTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.Stack" name="StackoperationsTryingEmptyEditor" time="5.260">
    <skipped/>
  </testcase> <!-- StackoperationsTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.Stack" name="StackoperationsTryingEmptyEditor" time="6.065">
    <skipped/>
  </testcase> <!-- StackoperationsTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.Stack" name="StackoperationsTryingEmptyEditor" time="7.180">
    <skipped/>
  </testcase> <!-- StackoperationsTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.Stack" name="StackoperationsTryingEmptyEditor" time="6.016">
    <skipped/>
  </testcase> <!-- StackoperationsTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.Stack" name="StackoperationsTryingValidAndInvalidCode" time="6.632"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="StackoperationsTryingValidAndInvalidCode" time="5.254"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="StackoperationsTryingValidAndInvalidCode" time="8.975"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="StackoperationsTryingValidAndInvalidCode" time="7.887"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="StackoperationsTryingValidAndInvalidCode" time="5.900"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="StackoperationsTryingValidAndInvalidCode" time="7.002"/>
  <system-out/>
</testsuite> <!-- testCases.Stack -->
